name: Build and deploy to pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Clean slate
        run: |
          rm -rf build
          rm -f elm.js
      - run: npm ci
      - run: npm run build
      - run: |
          mkdir build
          mv elm.js build/elm.js
          cp index.html build/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
